# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Androyara-build

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        
    - name: Build package
      run: |
        python -m pip install wheel
        python -m pip install twine
        python -m pip install -r requirements.txt
        python setup.py sdist bdist_wheel
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: copy wheel files
      shell: bash
      run: |
        echo "BuildVerson:  ${{ steps.get_version.outputs.VERSION }}"
        mv "dist/androyara*.whl" "androyara-release-${{ steps.get_version.outputs.VERSION }}-py3-none-any.whl"
        mv "dist/androyara*.gz" "androyara-release-${{ steps.get_version.outputs.VERSION }}.tar.gz"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: |
                androyara-release-${{ steps.get_version.outputs.VERSION }}
                androyara-release-${{ steps.get_version.outputs.VERSION }}.tar.gz
           
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
